services:
  db:
    image: "mysql:9.2"
    env_file: "./database/.env"
    ports:
      - "3306:3306"
    volumes:
      - commercedb:/data/db
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  commercedb:
